calibration:
  calib_mob_range: 0.3
  calib_mz_range: 2000
  calib_n_neighbors: 100
  calib_rt_range: 0.5
  outlier_std: 3
experiment:
  database_path: null
  fasta_paths:

  file_paths:

  fraction:
  - 1
  matching_group:
  - 0
  sample_group:
  - test
  shortnames:
  - alphapept_top_n10_peak300
failed:
  calibrate_hdf: []
  find_features: []
  raw_conversion: []
  score_hdf: []
fasta:
  AL_swap: false
  KR_swap: false
  fasta_block: 1000
  fasta_size_max: 100
  isoforms_max: 1024
  mods_fixed:
  - cC
  mods_fixed_terminal: []
  mods_fixed_terminal_prot: []
  mods_variable:
  - oxM
  - deamN
  - deamQ
  mods_variable_terminal: []
  mods_variable_terminal_prot:
  - a<^
  n_missed_cleavages: 2
  n_modifications_max: 5
  pep_length_max: 50
  pep_length_min: 7
  protease: trypsin
  pseudo_reverse: true
  save_db: true
  spectra_block: 100000
features:
  centroid_tol: 8
  hill_check_large: 40
  hill_length_min: 3
  hill_nboot: 150
  hill_nboot_max: 300
  hill_smoothing: 1
  hill_split_level: 1.3
  iso_charge_max: 5
  iso_charge_min: 2
  iso_corr_min: 0.6
  iso_mass_range: 5
  iso_n_seeds: 100
  iso_split_level: 1.3
  map_mob_range: 0.3
  map_mz_range: 1.5
  map_n_neighbors: 5
  map_rt_range: 0.5
  max_gap: 2
  search_unidentified: false
general:
  modfile_hash: 72252eb041669ea9b826e49f54a4ac50
  n_processes: 60
matching:
  match_d_min: 3
  match_group_tol: 0
  match_p_min: 0.05
quantification:
  lfq_ratio_min: 1
  max_lfq: true
  mode: ms1_int_sum_apex
raw:
  n_most_abundant: 300
  use_profile_ms1: false
score:
  method: random_forest
  ml_ini_score: generic_score
search:
  calibrate: true
  calibration_std_frag: 5
  calibration_std_prec: 5
  frag_tol: 20
  min_frag_hits: 5
  parallel: true
  peptide_fdr: 0.01
  ppm: true
  prec_tol: 20
  protein_fdr: 0.01
  recalibration_min: 100
  top_n: 10

workflow:
  align: true
  continue_runs: false
  create_database: true
  find_features: true
  import_raw_data: true
  lfq_quantification: false
  match: false
  recalibrate_data: false
  search_data: true