database_param:
  fragment_min_mz: 150.0
  fragment_max_mz: 1500.0
  enzyme_missed_cleavages: 2
  report_psms: 10
  digest_min_len: 7
  digest_max_len: 50
  enzyme_cleave_at: KR
  enzyme_restrict: P

  max_variable_mods: 3
  decoy_tag: rev_
  min_matched_peaks: 4
  max_fragment_charge: 2

  min_precursor_charge: 2
  max_precursor_charge: 5

  min_precursor_tol_ppm: -20
  max_precursor_tol_ppm: 20

  min_fragment_tol_ppm: -20
  max_fragment_tol_ppm: 20
  min_peaks: 15
  max_peaks: 150

fasta: ''

model_file: 'resource/model/mp_rank_00_model_states.pt'

gpu:
  max_member_use_rate: 0.5