# Spectrum processing options.
n_peaks: 300
min_mz: 50.0
max_mz: 2500.0
min_intensity: 0.01
remove_precursor_tol: 2.0
max_charge: 10
precursor_mass_tol: 50 # ppm
isotope_error_range: [0, 1]

# Model architecture options.
dim_model: 768
n_head: 16
dim_feedforward: 1024
n_layers: 9
dropout: 0
dim_intensity:
custom_encoder:

max_length: 50

n_log: 1
# input params
#data_path: ''
#model_path: ''

# out params
#tb_summarywriter: ""
#out_path: ""

warmup_ratio: 0.2 # warmup ratio of max_iters
learning_rate: 1e-6
min_lr: 1e-6
weight_decay: 5e-5
warmup_strategy: 'constant' # exp or cos
seed: 123

# Training/inference options
train_batch_size: 256 # the batch size of train phase
predict_batch_size: 512 # the batch size of val phase
buffer_size: 2 # 2000 # the buffer size of cistern
train_step_ratio: 0.9 # tensorboard monitor ratio of train phase
val_step_ratio: 0.8 # tensorboard monitor ratio of val phase

logger:
epochs: 10
